<?php 
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See LICENSE.txt for license details.
 */

/**
 * BlueFoot
 *
 * Version 1.0
 * @author Conor Farrell <conor@gene.co.uk>
 *
 * Carousel Template - this carousel uses the jQuery plugin Slick <http://kenwheeler.github.io/slick/>
 * Thanks to Ken Wheeler for allowing us to distribute his plugin with the Gene CMS
 *
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 */
$_entity = $this->getEntity();

if ($_entity->getShowDots()):
    $this->setCssClasses('bluefoot-slider-with-dots');
endif;
?>
<?php if ($this->hasChildEntities('advanced_slider_items')): ?>
    <?php $_collection = $this->getChildEntities('advanced_slider_items'); ?>
    <div id="bluefoot-advanced-slider-<?php echo $this->getEntity()->getId(); ?>" class="bluefoot-advanced-slider bluefoot-slider <?php echo $this->getCssAttributes(); ?>"<?php echo $this->getStyleAttributes(); ?>>
        <?php $_i = 0; foreach ($_collection as $_block): $_i++; ?>
            <?php echo $_block->setCount($_i)->toHtml(); ?>
        <?php endforeach; ?>
    </div>
    <?php if($this->helper('Magento\GoogleTagManager\Helper\Data')->isTagManagerAvailable()) :?>

        <script type="text/javascript">
            require([
                'jquery',
                'underscore'
            ], function ($, _) {
                'use strict';


                let gtmItem = [];

                if ($('[data-banner-id]').length) {

                    _.each($('[data-banner-id]'), function (banner) {

                        let id = $(banner).data('banner-id');
                        let creative = $(banner).data('banner-creative');
                        let position = $(banner).data('banner-position');
                        let name =  $(banner).data('banner-title');

                        gtmItem.push({
                            'id': id,
                            'name': name? name:'',
                            'creative': creative,
                            'position': position
                        });


                    });
                }

                window.dataLayer = window.dataLayer || [];
                dataLayer.push({
                    'event' : 'Promo Banners',
                    'ecommerce': {
                        'promoView': {
                            'promotions': gtmItem
                        }
                    }
                });

            });

        </script>
    <?php endif; ?>

    <script type="text/javascript">
        require(['jquery','slick'], function($) {
            $(function () {
                /* [Slick JS] */
                $('#bluefoot-advanced-slider-<?php echo $this->getEntity()->getId(); ?>').slick({
                    infinite: <?php echo ($_entity->getIsInfinite()) ? 'true' : 'false' ; ?>,
                    lazyLoad: 'ondemand',
                    dots: <?php echo ($_entity->getShowDots()) ? 'true' : 'false' ; ?>,
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    arrows: <?php echo ($_entity->getShowArrows()) ? 'true' : 'false' ; ?>,
                    autoplay: <?php echo ($_entity->getAutoplay()) ? 'true' : 'false' ; ?>,
                    autoplaySpeed: <?php echo ($_entity->getAutoplayPlaySpeed()) ? $_entity->getAutoplayPlaySpeed() : '5000' ; ?>,
                    fade: <?php echo ($_entity->getFade()) ? 'true' : 'false' ; ?>,
                    prevArrow: '<button type="button" class="slick-prev button"><span><span>&lt;</span></span></button>',
                    nextArrow: '<button type="button" class="slick-next button"><span><span>&gt;</span></span></button>'
                    <?php echo ($_entity->getSliderAdditionalSettings()) ? ',' . $_entity->getSliderAdditionalSettings()  : '' ; ?>
                });
            });

            $('#bluefoot-advanced-slider-<?php echo $this->getEntity()->getId(); ?>').on('init', function(event, slick){
                slick.$slider.addClass('slick-visible');
            });
            // Fallback if init function fails
            $(window).load(function(){
                $('#bluefoot-advanced-slider-<?php echo $this->getEntity()->getId(); ?>').addClass('slick-visible');
            });
        });
    </script>

<?php endif; ?>