<?php 
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See LICENSE.txt for license details.
 */

/**
 * BlueFoot
 *
 * Version 1.0
 * @author Conor Farrell <conor@gene.co.uk>
 *
 * Carousel Template - this carousel uses the jQuery plugin Slick <http://kenwheeler.github.io/slick/>
 * Thanks to Ken Wheeler for allowing us to distribute his plugin with the Gene CMS
 *
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 */
$_entity = $this->getEntity();
$_urlPrefix = $block->getMediaUrl() . 'gene-cms';
?>
<?php if ($this->hasChildEntities('customer_quotes_slider_item')): ?>

    <?php $_collection = $this->getChildEntities('customer_quotes_slider_item'); ?>

    <div class="customer-quote-wrapper">
        <div class="customer-quote-title">
            <h2><?php echo __('מה אומרים עלינו...');?></h2>
        </div>
        <div class="quote-icon"></div>

        <ul id="customer-quotes-slider-<?php echo $this->getEntity()->getId(); ?>"
            class="slider-for <?php echo $this->getCssAttributes(); ?>"<?php echo $this->getStyleAttributes(); ?>>
            <?php $_i = 0; foreach ($_collection as $_block): $_i++; ?>
                <?php if ($_i < 5): ?>
                    <?php echo $_block->setCount($_i)->toHtml(); ?>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>

        <div id="sh-slider-nav-<?php echo $this->getEntity()->getId(); ?>" class="slider-nav">
            <?php $_i = 0; foreach ($_collection as $_block): $_i++; ?>
                <?php if ($_i < 5): ?>
                    <div class="sh-slider-nav-item">
                        <div class="info-wrapper">
                            <div class="sh-block-1">
                                <div class="sh-fname"><?php echo $_block->getEntity()->getFirstName();?></div>
                                <div class="sh-info"> <?php echo $_block->getEntity()->getExtraInfo();?></div>
                            </div>
                            <div class="sh-block-2">
                                <img src="<?php echo $_urlPrefix . $_block->getEntity()->getImage();?>" alt="">
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>

        <script type="text/javascript">
            require(['jquery','slick'], function($) {

                $(function () {
                    /* [Slick JS] */
                    $('#customer-quotes-slider-<?php echo $this->getEntity()->getId(); ?>').slick({
                        infinite: true,
                        lazyLoad: 'ondemand',
                        rtl: true,
                        asNavFor: '.slider-nav',
                        dots: false,
                        slidesToShow: 1,
                        slidesToScroll: 1,
                        responsive: [
                            {
                                breakpoint: 1024,
                                settings: {
                                    infinite: true
                                }
                            },
                            {
                                breakpoint: 768,
                                settings: {
                                    infinite: true
                                }
                            },
                            {
                                breakpoint: 480,
                                settings: {
                                    infinite: true
                                }
                            }
                        ],
                        arrows: false,
                        autoplay: false,
                        autoplaySpeed: 5000,
                        fade: false,
                        prevArrow: '<button type="button" class="slick-prev button"><span><span>&lt;</span></span></button>',
                        nextArrow: '<button type="button" class="slick-next button"><span><span>&gt;</span></span></button>'
                        <?php echo ($_entity->getSliderAdditionalSettings()) ? ',' . $_entity->getSliderAdditionalSettings()  : '' ; ?>
                    });

                    $('#sh-slider-nav-<?php echo $this->getEntity()->getId(); ?>').slick({
                        infinite: true,
                        lazyLoad: 'ondemand',
                        dots: false,
                        slidesToShow: 4,
                        rtl: true,
                        focusOnSelect: true,
                        asNavFor: '.slider-for',
                        slidesToScroll: 1,
                        arrows: false,
                        autoplay: false,
                        autoplaySpeed: 5000,
                        fade: false,
                        focusOnSelect: true,
                        responsive: [
                            {
                                breakpoint: 1024,
                                settings: {
                                    slidesToShow: 3,
                                    slidesToScroll: 1,
                                    infinite: true
                                }
                            },
                            {
                                breakpoint: 768,
                                settings: {
                                    slidesToShow: 2,
                                    slidesToScroll: 1,
                                    infinite: true
                                }
                            },
                            {
                                breakpoint: 480,
                                settings: {
                                    slidesToShow: 1,
                                    slidesToScroll: 1,
                                    infinite: true
                                }
                            }
                        ],
                        prevArrow: '<button type="button" class="slick-prev button"><span><span>&lt;</span></span></button>',
                        nextArrow: '<button type="button" class="slick-next button"><span><span>&gt;</span></span></button>'
                        <?php echo ($_entity->getSliderAdditionalSettings()) ? ',' . $_entity->getSliderAdditionalSettings()  : '' ; ?>
                    });
                });

                $('#customer-quotes-slider-<?php echo $this->getEntity()->getId(); ?>').on('init', function(event, slick){
                    slick.$slider.addClass('slick-visible');
                });
                $('#sh-slider-nav-<?php echo $this->getEntity()->getId(); ?>').on('init', function(event, slick){
                    slick.$slider.addClass('slick-visible');
                });
                // Fallback if init function fails
                $(window).load(function(){
                    $('#customer-quotes-slider-<?php echo $this->getEntity()->getId(); ?>').addClass('slick-visible');
                    $('#sh-slider-nav-<?php echo $this->getEntity()->getId(); ?>').addClass('slick-visible');
                });
            });
        </script>
    </div>
<?php endif; ?>