<?php 
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See LICENSE.txt for license details.
 */

/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Image Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $this->getEntity();
$_urlPrefix = $block->getMediaUrl() . 'gene-cms';
?>
<figure id="sh-hero-banner-image-<?php echo $_entity->getId(); ?>" class="sh-hero-banner-image bluefoot-image <?php echo $this->getCssAttributes(); ?>"<?php echo $this->getStyleAttributes(); ?>>
    <a href="<?php echo $_entity->getLinkUrl(); ?>">
            <?php if ($_entity->getMobileImage()): ?>
                <img src="<?php echo $_urlPrefix . $_entity->getImage(); ?>"  alt="<?php echo $_entity->getAltTag(); ?>" title="<?php echo $_entity->getTitleTag(); ?>" class="bluefoot-mobile-hidden"/>
                <img src="<?php echo $_urlPrefix . $_entity->getMobileImage(); ?>"  alt="<?php echo $_entity->getAltTag(); ?>" title="<?php echo $_entity->getTitleTag(); ?>" class="bluefoot-mobile-only"/>
            <?php else: ?>
                <img src="<?php echo $_urlPrefix . $_entity->getImage(); ?>"  alt="<?php echo $_entity->getAltTag(); ?>" title="<?php echo $_entity->getTitleTag(); ?>" />
            <?php endif; ?>
    </a>
    <?php if ($_entity->getShowCaption() && $_entity->getTitleTag()): ?>
        <figcaption>
            <?php echo $_entity->getTitleTag(); ?>
        </figcaption>
    <?php endif; ?>
</figure>