<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Youre done Continue shopping cart'); ?>
<?php if ($_product->isSaleable()): ?>

<?php endif; ?>


<?php if( !$block->getHideAddtoCart() ||
    ($_product->getTypeID() != "simple") ||
    !($_product->getTypeID() == "simple" && $block->getHideAddtoCart() == 1)
):?>
    <?php if ($block->isRedirectToCartEnabled()) : ?>

        <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "Magento_Catalog/product/view/validation": {
                    "radioCheckboxClosest": ".nested"
                }
            }
        }
    </script>
    <?php else : ?>
        <script>
            require([
                'jquery',
                'mage/mage',
                'Magento_Catalog/product/view/validation',
                'Magento_Catalog/js/catalog-add-to-cart'
            ], function ($) {
                'use strict';

              //floating button


                let topheight = ($('.mix-and-match-breadcrumb').height()) + ($('.top-dec').outerHeight() + 450);
                let scrennheightmobile= ($(".fieldset-bundle-options").outerHeight() - topheight );
                let scrennheightdesktop= $(".fieldset-bundle-options").outerHeight() - topheight;

                let addToCartButton = $('#product-addtocart-button');

                let duration = 500;

                jQuery(window).scroll(function() {

                    if ($(window).width() < 480) {
                        if (jQuery(this).scrollTop() < scrennheightmobile) {
                            addToCartButton.fadeIn(duration).addClass('floating');
                            // jQuery(addToCartButton).width(jQuery(window).width());
                        } else {
                            addToCartButton.fadeIn(duration).removeClass('floating');
                        }
                    }

                    else {
                        if (jQuery(this).scrollTop() < scrennheightdesktop) {

                            addToCartButton.fadeIn(duration).addClass('floating');

                        } else {
                            addToCartButton.removeClass('floating');
                        }
                    }


                });


            });
        </script>
    <?php endif; ?>
<?php endif; ?>
